# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  kubernetes: circleci/kubernetes@1.3.1
  docker: circleci/docker@2.1.2

jobs:
  staging-cluster-deploy:
    description: Staging Cluster Deploy
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    resource_class: medium
      
    working_directory: ~/docs
    
    steps:
      - checkout
      - kubernetes/install-kubectl:
        kubectl-version: latest 

      - kubernetes/install-kubeconfig:
        kubeconfig: KUBECONFIG_DATA
        
      - kubernetes/create-or-update-resource:
          resource-name: deployment/docs
          show-kubectl-command: true 
          get-rollout-status: true 
          resource-file-path: .circleci/deployment.yml 
          server-side-apply: true
          action-type: apply
          envsubst: true

  production-cluster-deploy:
    description: Production Cluster Deploy
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    resource_class: medium
      
    working_directory: ~/docs
    
    steps:
      - checkout
      - kubernetes/install-kubectl:
        kubectl-version: latest 

      - kubernetes/install-kubeconfig:
        kubeconfig: KUBECONFIG_DATA
      
      - kubernetes/create-or-update-resource:
          resource-name: deployment/docs
          show-kubectl-command: true 
          get-rollout-status: true 
          resource-file-path: .circleci/deployment.yml 
          server-side-apply: true
          action-type: apply
          envsubst: true

workflows:
  version: 2
  docs-deployment-workflow:
    jobs:
      - deployment-approval:
          name: Waiting approval
          type: approval
          
      - staging-cluster-deploy:
          name: Deploy to Staging Cluster
          context:
            - DOCKER_PERSONAL
          filters:
            branches:
              ignore:
                - master
                - main
          requires:
            - Waiting approval
            
      - production-cluster-deploy:
          name: Deploy to Production Cluster
          context:
            - DOCKER_PERSONAL
          filters:
            branches:
              only:
                - master
                - main
          requires:
            - Waiting approval
