---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mkdocs
  namespace: docs
  labels:
    allow.http: "false"
    application: mkdocs
spec:
  replicas: 3
  selector:
    matchLabels:
      application: mkdocs
  template:
    metadata:
      labels:
        application: mkdocs
    spec:
      containers:
      - name: mkdocs
        image: squidfunk/mkdocs-material
        ports:
        - containerPort: 80
        securityContext:
          privileged: false
  
---
apiVersion: v1
kind: Service
metadata:
  name: mkdocs
  namespace: docs
spec:
  type: ClusterIP
  ports:
  - port: 80 # Porta a ser exposta pelo SERVICE
    targetPort: 8000 # Porta que a aplicação está rodando no POD
  selector:
    application: mkdocs
    
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: mkdocs
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: default
spec:
  rules:
    - host: docs.shafitycore.cyou
      http:
        paths:
          - path : /
            pathType: Prefix
            backend:
              service:
                name: mkdocs
                port:
                  number: 80
